blog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /blog/
    # path('', views.index, name='index'),
    path('', views.index, name='index'),
    path('addcomment/<int:id>/<slug:slug>/', views.addcomment, name='addcomment'),

]

home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index, name='index'),


    ]

mysite/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.urls import path, include
import os

from home import views

BASE_DIR = os.path.dirname(os.path.dirname(__file__))
urlpatterns = [
    path('user/', include('user.urls')),
    path('', include('home.urls')),
    path('aboutus', views.aboutus, name='aboutus'),
    path('contactus', views.contactus, name='contactus'),
    path('referance', views.references, name='referance'),
    path('home/', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('category/<int:id>/<slug:slug>/', views.category_blogs, name='category_blogs'),
    path('blog/<int:id>/<slug:slug>/', views.blog_detail, name='blog_detail'),
    path('blog/<int:id>/<slug:slug>/like', views.blog_like_unlike, name='blog_like_unlike'),
    path('search/', views.blog_search,name= 'blog_search'),
    path('search_auto/', views.blog_search_auto, name='blog_search_auto'),
    path('logout/',views.logout_views,name='logout_views'),
    path('login/',views.login_views,name='login_views'),
    path('register/', views.register_views, name='register_views'),
    path('userpage/', views.userpage, name='userpage'),
    path('useraddblog/', views.useraddblog, name='useraddblog'),
    path('userblogs/', views.userblogs, name='userblogs'),
    path('usercomments/', views.usercomments, name='usercomments'),
    path('userbloglikes/', views.userlikes, name='userbloglikes'),
    path('deleteusercomment/<int:id>', views.deleteusercomment, name='deleteusercomment'),
    path('question/', views.question, name='question'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm
from django.urls import reverse
from django.utils.safestring import mark_safe
from ckeditor_uploader.fields import RichTextUploadingField
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel
from home.models import userProfile


class Category(MPTTModel):
    STATUS = (
        ('true', 'True'),
        ('false', 'False')
    )
    # author = models.TextField(max_length=50)
    title = models.CharField(max_length=50)
    keywords = models.CharField(max_length=50)
    description = models.CharField(max_length=50)
    image = models.ImageField(blank=True, upload_to='images/')
    status = models.CharField(max_length=10, choices=STATUS)
    slug = models.SlugField(null=False, unique=True)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    content = RichTextUploadingField()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class MPTTMeta:
        order_insertion_by = ['title']

    def __str__(self):
        full_path = [self.title]
        k = self.parent
        while k is not None:
            full_path.append(k.title)
            k = k.parent
        return '--> '.join(full_path[::-1])

    def image_tag(self):
        if self.image and hasattr(self.image, 'url'):
            return mark_safe('<img src="{}" height="50" width="100"/>'.format(self.image.url))

    image_tag.short_description = 'Image'

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})


class BlogLike(models.Model):
    blog = models.ForeignKey('Blog', null=True, blank=True, on_delete=models.CASCADE)
    user = models.ForeignKey(userProfile, null=True, blank=True, on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.blog.title


class Blog(models.Model):
    STATUS = (
        ('true', 'True'),
        ('false', 'False ')
    )
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    author = models.CharField(max_length=50)
    title = models.CharField(max_length=50)
    keywords = models.CharField(max_length=50)
    description = models.CharField(max_length=50)
    image = models.ImageField(blank=True, upload_to='images/')
    status = models.CharField(max_length=10, choices=STATUS, default='false')
    slug = models.SlugField(unique=True, null=False)
    parent = models.ForeignKey('self', blank=True, null=True, related_name='children', on_delete=models.CASCADE)
    detail = RichTextUploadingField()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def image_tag(self):
        if self.image and hasattr(self.image, 'url'):
            return mark_safe('<img src="{}" height="50" width="100"/>'.format(self.image.url))

    image_tag.short_description = 'Image'

    def get_absolute_url(self):
        return reverse('blog_detail', kwargs={'slug': self.slug})

    @property
    def get_likes(self):
        return BlogLike.objects.filter(blog=self)

    @property
    def images(self):
        return Images.objects.filter(Blog=self)


class Images(models.Model):
    Blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    image = models.ImageField(blank=True, upload_to='images/')

    def __str__(self):
        return self.title

    def image_tag(self):
        if self.image and hasattr(self.image, 'url'):
            return mark_safe('<img src="{}" height="50" width="100"/>'.format(self.image.url))

    image_tag.short_description = 'Image'


class Comment(models.Model):
    STATUS = (
        (' New', 'New'),
        ('true', 'True'),
        ('false', 'False ')
    )

    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=50)
    email = models.CharField(max_length=50, blank=True)
    website = models.CharField(max_length=50, blank=True)
    comment = models.TextField(max_length=200, blank=True)
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=20)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.subject


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['subject', 'email', 'website', 'comment']

blog/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

from blog.models import CommentForm, Comment


def index(request):
    return HttpResponse("welcome to Blog page")


@login_required(login_url='/login')
def addcomment(request, id,slug):
    url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            current_user = request.user
            data = Comment()
            data.user_id = current_user.id
            data.blog_id = id
            data.blog_slug=slug
            data.subject = form.cleaned_data['subject']
            data.email = form.cleaned_data['email']
            data.website = form.cleaned_data['website']
            data.comment = form.cleaned_data['comment']
            data.ip = request.META.get('REMOTE_ADDR')
            data.save()
            messages.success(request, "your mesaj has successfly sent")
            return HttpResponseRedirect(url)
    messages.warning(request, "did not send , please check fields")
    return HttpResponseRedirect(url)

home/views.py
import json

from django.contrib.auth import logout, authenticate, login
from django.contrib import messages
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect

from blog.models import Blog, Category, Images, Comment, BlogLike
from home.form import SearchForm, RegisterForm
from home.models import Setting, contactusform, userProfile


def index(request):
    setting = Setting.objects.get(pk=1)
    sliderdata = Blog.objects.all()[:3]
    category = Category.objects.all()
    lastBlogs = Blog.objects.all()[:2]
    blog = Blog.objects.filter(status='true')[:10]
    context = {'setting': setting, 'page': 'home',
               'sliderdata': sliderdata,
               'category': category,
               'lastBlogs': lastBlogs,
               'blog': blog, }
    return render(request, 'index.html', context)


def aboutus(request):
    setting = Setting.objects.get(pk=1)
    sliderdata = Blog.objects.all()[:3]
    category = Category.objects.all()
    lastBlogs = Blog.objects.all()[:1]
    context = {'setting': setting,
               'category': category,
               'sliderdata': sliderdata,
               'lastBlogs': lastBlogs}
    return render(request, 'aboutus.html', context)


def contactus(request):
    form = contactusform(request.POST or None, request.FILES or None)
    if form.is_valid():
        form.save()
        messages.success(request, "your comment has sent successfly ")
        return HttpResponseRedirect('/contactus')
    setting = Setting.objects.get(pk=1)
    sliderdata = Blog.objects.all()[:3]
    lastBlogs = Blog.objects.all()[:1]
    form = contactusform()
    category = Category.objects.all()
    context = {'setting': setting, 'form': form,
               'category': category,
               'sliderdata': sliderdata,
               'lastBlogs': lastBlogs}
    return render(request, 'contactus.html', context)


def references(request):
    setting = Setting.objects.get(pk=1)
    sliderdata = Blog.objects.all()[:3]
    category = Category.objects.all()
    lastBlogs = Blog.objects.all()[:1]
    context = {'setting': setting,
               'category': category,
               'sliderdata': sliderdata,
               'lastBlogs': lastBlogs}
    return render(request, 'referances.html', context)


def category_blogs(request, id, slug):
    category = Category.objects.all()
    categorydata = Category.objects.get(pk=id)
    sliderdata = Blog.objects.all()[:3]
    lastBlogs = Blog.objects.all()[:1]
    blogs = Blog.objects.filter(category_id=id)
    context = {'blogs': blogs,
               'category': category,
               'sliderdata': sliderdata,
               'categorydata': categorydata,
               'lastBlogs': lastBlogs}
    return render(request, 'blogs.html', context)


def blog_detail(request, id, slug):
    category = Category.objects.all()

    blog = Blog.objects.get(pk=id)
    lastBlogs = Blog.objects.all()[:2]
    images = Images.objects.filter(Blog_id=id)
    comments = Comment.objects.filter(blog_id=id, status='true')
    if request.user.is_authenticated:
        profile = userProfile.objects.get(user=request.user)
        didLiked = BlogLike.objects.filter(blog=blog, user=profile)
    else:
        profile = None
        didLiked = False
    context = {'blog': blog,
               'category': category,
               'images': images,
               'comments': comments,
               'lastBlogs': lastBlogs,
               'profile': profile,
               'didLiked': didLiked
               }
    return render(request, 'blog_detail.html', context)


def blog_like_unlike(request, id, slug):
    blog = Blog.objects.get(pk=id)
    profile = userProfile.objects.get(user=request.user)
    blogLike = BlogLike.objects.filter(blog=blog, user=profile)
    if len(blogLike) == 0:
        BlogLike(blog=blog, user=profile).save()
    else:
        blogLike.delete()

    return redirect(f'/blog/{id}/{slug}/')


def blog_search(request):
    if request.method == 'POST':
        form = SearchForm(request.POST)
        # print(form.errors)
        if form.is_valid():
            category = Category.objects.all()
            sliderdata = Blog.objects.all()[:3]
            # lastBlogs = Blog.objects.all()[:3]
            query = form.cleaned_data['query']
            blogs = Blog.objects.filter(title__icontains=query)
            context = {'blogs': blogs,
                       'category': category,
                       'sliderdata': sliderdata,
                       }

            return render(request, 'blogs_search.html', context)

    return HttpResponseRedirect('/')


def blog_search_auto(request):
    query = request.GET.get('query')
    if query is None:
        return HttpResponse(json.dumps({}))
    if len(query) == 0:
        return HttpResponse(json.dumps({}))
    blogs = Blog.objects.filter(title__icontains=query)
    result = {}
    for blog in blogs:
        result[blog.id] = [blog.slug, blog.title]
    return HttpResponse(json.dumps(result))


def logout_views(request):
    logout(request)
    return HttpResponseRedirect('/')


def login_views(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect('/')
        else:
            messages.warning(request, "check your username or password")
            return HttpResponseRedirect('/login')

    category = Category.objects.all()
    context = {'category': category,
               }
    return render(request, 'login.html', context)


def register_views(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = request.POST['username']
            password = request.POST['password1']

            user = authenticate(request, username=username, password=password)
            login(request, user)
            return HttpResponseRedirect('/')

    form = RegisterForm()
    category = Category.objects.all()
    context = {'category': category,
               'form': form,
               }
    return render(request, 'register.html', context)


def userpage(request):
    category = Category.objects.all()
    profile = userProfile.objects.get(user=request.user)
    context = {'category': category,
               'profile': profile
               }
    # print(profile.username)
    return render(request, 'user_info.html', context)


def useraddblog(request):
    category = Category.objects.all()
    profile = userProfile.objects.get(user_id=request.user.id)

    context = {'category': category,
               'profile': profile
               }
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        keywords = request.POST.get('keywords')
        detail = request.POST.get('detail')
        slug = request.POST.get('slug')
        categoryId = request.POST.get('category')
        image = request.FILES.get('image')
        category2 = Category.objects.get(pk=categoryId)
        auther = request.POST.get('auther')
        user = User.objects.get(username=request.user)

        b = Blog(category=category2, user=user, author=auther, title=title, keywords=keywords, description=description,
                 image=image, slug=slug, parent=None, detail=detail)
        b.save()
        return redirect('/home/')
    return render(request, 'user_add_blog.html', context)


def userblogs(request):
    category = Category.objects.all()
    user = request.user
    myblogs = Blog.objects.filter(user_id=user.id)
    print(myblogs)
    context = {'category': category,

               'myblogs': myblogs,
               }
    return render(request, 'userblogs.html', context)


def usercomments(request):
    category = Category.objects.all()
    user = request.user
    mycomments = Comment.objects.filter(user_id=user.id)
    context = {'category': category,

               'mycomments': mycomments,
               }
    return render(request, 'usercomments.html', context)


def userlikes(request):
    category = Category.objects.all()
    user = userProfile.objects.get(user=request.user)
    blogLikes = BlogLike.objects.filter(user=user)
    context = {'category': category,

               'blogLikes': blogLikes,
               }
    return render(request, 'userlikes.html', context)


def question(request):
    return HttpResponse("question page ")


def deleteusercomment(request, id):
    delete = Comment.objects.get(pk=id)
    delete.delete()
    return redirect('/usercomments')

home/templates/aboutus.html
{% extends 'homebase.html' %}

{% block title%} About{{setting.company}} {% endblock%}
{% block keywords%} {{setting.keywords}}  {% endblock%}
{% block description%} {{setting.description} {% endblock%}
{% block head%}<link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url}}'/> {%endblock%}
{% block header%} {% include 'header.html'%}{% endblock%}
{% block sidebar%} {% include 'sidebar.html'%}{% endblock%}
{% block slider%} {% include 'slider.html'%}{% endblock%}
{% block content%}
<div class="clearfix"> </div>
<!--			    <div class="b-bottom">-->
<!--			      <h5 class="top"><a href="single.html">What turn out consetetur sadipscing elit</a></h5>-->
<!--			      <p>On Aug 25 <a class="span_link" href="#"><span class="glyphicon glyphicon-comment"></span>0 </a><a class="span_link" href="#"><span class="glyphicon glyphicon-eye-open"></span>56 </a><a class="span_link" href="single.html"><span class="glyphicon glyphicon-circle-arrow-right"></span></a></p>-->
<!--				</div>-->
			 </div>
<div class="container">
	 <div class="top-news">
    <div class="top-inner">
        {{setting.about_us|safe}}
	 </div>
 </div>
</div>

</div>

 {% endblock%}
{% block banner%} {% include 'banner.html'%}{% endblock%}
{% block footer%} {% include 'footer.html'%}{% endblock%}

home/templates/banner.html
{% load static%}
<div class="banner-right-text" style="z-index: 0;">
    <h3 class="tittle">Categories </h3>
    <!--/general-news-->
    <div class="general-news">
        <div class="general-inner">
            <div class="general-text">

            </div>
            <div class="edit-pics">
                <div class="editor-pics">
					{% for rs in category %}
                        <div class="col-md-3 item-pic">
                           <a href="/category/{{rs.id}}/{{rs.slug}}"> <img src="{{rs.image.url}}" class="img-responsive" alt=""> </a>
                        </div>
                        <div class="col-md-9 item-details">
                            <h5 class="inner two"><a href="/category/{{rs.id}}/{{rs.slug}}">{{ rs.title}}</a></h5>
                            <div class="td-post-date two"><i class="glyphicon glyphicon-time"></i>{{rs.created_on}}
                                <a href="#"><i class="glyphicon glyphicon-comment"></i>0 </a></div>
                        </div>

                    <div class="clearfix"></div><br>
                    {% endfor%}
                </div>
            </div>
            <div class="media">
                <h3 class="tittle media">Last Blogs  <i class="glyphicon glyphicon-floppy-disk"></i></h3>
                {% for rs in lastBlogs %}
                <div class="general-text two">
                    <a href="/blog/{{rs.id}}/{{rs.slug}}"><img src="{{ rs.image.url }}" class="img-responsive" alt=""></a>
                    <h5 class="top"><a href="single.html">{{rs.title}}</a></h5>
                    <p>{{rs.detail | safe}}</p>
                    <p>On Jun 27 <a class="span_link" href="#"><span class="glyphicon glyphicon-comment"></span>0 </a><a
                            class="span_link" href="#"><span class="glyphicon glyphicon-eye-open"></span>56 </a><a
                            class="span_link" href="single.html"><span
                            class="glyphicon glyphicon-circle-arrow-right"></span></a></p>
                </div>
                {% endfor %}
            </div>

        </div>
    </div>
</div>
<div class="clearfix"></div>

home/templates/blog_detail.html
{% extends 'homebase.html' %}

{% block title%} {{blog.title}} {% endblock%}
{% block keywords%} {{blog.keywords}}  {% endblock%}
{% block description%} {{blog.description} {% endblock%}
{% block head%}
<link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url}}'/> {%endblock%}
{% block header%} {% include 'header.html'%}{% endblock%}
{% block sidebar%} {% include 'sidebar.html'%}{% endblock%}

{% block content%}
<div class="col-md-9 main">
    <!--banner-section-->
    <div class="banner-section">
        <h3 class="top"><a href="/category/{{blog.category_id}}/{{blog.category.slug}}" style="text-decoration: underline"> CATEGORY_{{ blog.category }}</a></h3>
        <HR>
<!--            <div class="banner">-->
<!--                 <div  class="callbacks_container">-->
<!--					<ul class="rslides" id="slider4">-->
<!--						{% for img in blog.images %}-->
<!--							<li>-->
<!--								  <img src="{{ img.image.url}}"  width="800px"  height="200" />-->
<!--								</li>-->

<!--						{% endfor %}-->
<!--						</ul>-->
<!--					</div>-->
<!--					&lt;!&ndash;banner&ndash;&gt;-->

<!--			 <script>-->
<!--			    // You can also use "$(window).load(function() {"-->
<!--			    $(function () {-->
<!--			      // Slideshow 4-->
<!--			      $("#slider4").responsiveSlides({-->
<!--			        auto: true,-->
<!--			        pager:true,-->
<!--			        nav:true,-->
<!--			        speed: 500,-->
<!--			        namespace: "callbacks",-->
<!--			        before: function () {-->
<!--			          $('.events').append("<li>before event fired.</li>");-->
<!--			        },-->
<!--			        after: function () {-->
<!--			          $('.events').append("<li>after event fired.</li>");-->
<!--			        }-->
<!--			      });-->

<!--			    });-->
<!--			  </script>-->
<!--            </div>-->
        <div class="single">
            <img src="{{ blog.image.url }}" class="" alt="" width="800" height="400" align="center"/>
            <hr>
            <h3 class="tittle">{{ blog.title }}<i class="glyphicon glyphicon-file"></i></h3>

            <br>
            <table>
                <tr>
                    <th>
                        Other Images
                    </th>
                </tr>
                {% for rs in images %}
                <tr>
                    <img src="{{ rs.image.url }}" height="100" width="100" alt="Avatar" style="border-radius:50%"/>
                </tr>
                {% endfor %}
            </table>
            <div class="b-bottom">
            </div>
        </div>

        <div class="single-bottom">
            <div class="single-middle">
                <h4> Post </h4>
                <ul class="social-share">
                    <li><span>{{ blog.detail | safe }}</span></li>
<!--                    <li><a href="#"><i> </i></a></li>-->
<!--                    <li><a href="#"><i class="tin"> </i></a></li>-->
<!--                    <li><a href="#"><i class="message"> </i></a></li>-->
                </ul>

<!--                <a href="#"><i class="arrow"> </i></a>-->
                <div class="clearfix"></div>
                <br><br>
                {% if request.user.is_authenticated %}
                <a href="{% url 'blog_like_unlike' id=blog.id slug=blog.slug %}" class="btn btn-success float-right">{% if didLiked %} Unliked {% else %} Like {% endif %}</a>
                {% endif %}
            </div>

        </div>
        <div class="response">
            <h4>Responses</h4>
            {% for rs in comments %}
            <div class="media response-info">
                <div class="media-left response-text-left">
                    <a href="#">
                        <img class="media-object" src="images/sin1.jpg" alt=""/>
                    </a>
                    <h5><a href="#">{{rs.user.username}}</a></h5>
                    <a href="#"> <img src="{{ profile.image.url}} " height="50" width="50"></a>
                </div>
                <div class="media-body response-text-right">
                    <p>{{ rs.comment }}</p>
                    <ul>
                        <li>
                        <li>{{ rs.created_on}}</li>
                        <li><a href="single.html">Reply</a></li>
                    </ul>
                </div>
                <div class="clearfix"></div>
            </div>
            {% endfor %}


        </div>
        <div class="coment-form">
            <h4>Leave your comment</h4>
            {% if messages %}
					{% for msg in messages %}
						<div class="alert alert-{{ msg.tags }}" role="alert"> {{ msg }}</div>

					{% endfor %}
				{% endif %}
            <form method="post" action="/blog/addcomment/{{blog.id}}/{{blog.slug}}/">
                {% csrf_token %}
                <input type="text" name="subject" id="id_subject" placeholder="subject">
                <input type="email" name="email" id="id_email" placeholder="email">
                <input type="text" name="website" id="id_website" placeholder="website">
                <textarea name="comment" id="id_comment" placeholder="comment here..."></textarea>

                {% if user.id is not None %}
                <input type="submit" value="Submit Comment">

                {% else %}
                You need Login for comment
                {% endif %}
            </form>

        </div>
        <div class="clearfix"></div>
    </div>
    <!--//banner-->
    <!--//banner-section-->

    {% endblock%}
    {% block banner%} {% include 'banner.html'%}{% endblock%}
    {% block footer%} {% include 'footer.html'%}{% endblock%}

home/templates/contactus.html
{% extends 'homebase.html' %}

{% block title%} Contact{{setting.company}} {% endblock%}
{% block keywords%} {{setting.keywords}}  {% endblock%}
{% block description%} {{setting.description} {% endblock%}
{% block head%}<link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url}}'/> {%endblock%}
{% block header%} {% include 'header.html'%}{% endblock%}
{% block sidebar%} {% include 'sidebar.html'%}{% endblock%}
{% block slider%} {% include 'slider.html'%}{% endblock%}
{% block content%}
<div class="clearfix"> </div>

			 </div>
<br>

	<div class="col-4">
		<div class="row-md-5 ">
			<div class="top-news">
				<div class="top-inner">
					{{setting.contact|safe}}
				 </div>
			</div>
		</div>

			{% if messages %}
				<ul class="messages">
					{% for message in messages %}
						<li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
					{% endfor %}
				</ul>
			{% endif %}
		<div class="row-md-8" >
			<h1 align="center"> Contact Us </h1>
			<br><br>
			<form action="" method="post">
				{% csrf_token %}
				{{ form.as_p}}
				<br><input type="submit" value="Send MSG">
			</form>
		</div>
	</div>

</div>

 {% endblock%}
{% block banner%} {% include 'banner.html'%}{% endblock%}
{% block footer%} {% include 'footer.html'%}{% endblock%}

home/templates/header.html
<div class="h-top" id="home">
    <div class="top-header">
        <ul class="cl-effect-16 top-nag">
            <li><a href="/">Home</a></li>
            <li><a href="/aboutus" data-hover="About">About</a></li>
            <li><a href="/contactus" data-hover="CONTACT">Contact</a></li>
            <li><a href="/referance">Referances</a></li>


            {% if user.id is not None %}
            <li><a href="/logout/" data-hover="logout">Logout</a></li>

            <li><a href="/userpage" data-hover=" User:{{user.first_name }}"> User:{{user.first_name }} </a></li>

            {% else %}
            <li><a href="/login/" data-hover="Login">Login</a></li>
            <li><a href="/register/" data-hover="Registration">Registration</a></li>
            {% endif %}
        </ul>

        <div class="search-box" style="z-index: 9999;">
            <div class="b-search">
                <form method="post" action="/search/">
                    {% csrf_token %}
                    <input name="query" id="query" type="text" value="Search" onfocus="this.value = '';"
                           onblur="if (this.value == '') {this.value = 'Search';}">
                    <input type="submit" value=" ">
                    <div id="search_result" style="
                    position: absolute;
                    top: 45px;
                    right: 0px;
                    background-color: white;
                    width: 237px;
                    z-index: 9999999999;
                        ">
                    </div>
                    <script>
                                $("#query").on("change paste keyup", function () {
                                    const search_result = $('#search_result');
                                    const q = $('#query').val();
                                    if(q.length == 0)
                                    {
                                        search_result.empty();
                                        return;
                                    }
                                    $.get(`/search_auto/?query=${q}`, function (data) {
                                        data = JSON.parse(data.toString());
                                        search_result.empty();
                                        for (var key in data) {
                                            search_result.append(
                                                `<a href="/blog/${key}/${data[key][0]}/" style="display: block; padding: 10px 5px; background: rgb(200, 200, 200); color: white; z-index: 99999999000000;">${data[key][1]}</a>`
                                            )
                                        }
                                    });
                                });

                    </script>
                </form>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>

home/templates/questions.html
{% extends 'user_profile.html'%}
{% block user_page %}
bchsabchj
{% endblock %}

home/templates/slider.html
{% load static%}
<div class="col-md-9 main">
		<!--banner-section-->
		<div class="banner-section">
		   <h3 class="tittle">General <i class="glyphicon glyphicon-picture"></i></h3>
			<div class="banner">
                 <div  class="callbacks_container">
					<ul class="rslides" id="slider4">
						{% for rs in sliderdata %}
							<li>
								  <a href="/blog/{{rs.id}}/{{rs.slug}}"><img src="{{ rs.image.url}}"  width="800px"  height="200" /></a>
									<h2>{{ rs.description}}</h2>
								</li>

						{% endfor %}
						</ul>
					</div>
					<!--banner-->
	  			<script src="{% static 'js/responsiveslides.min.js '%}"></script>
			 <script>
			    // You can also use "$(window).load(function() {"
			    $(function () {
			      // Slideshow 4
			      $("#slider4").responsiveSlides({
			        auto: true,
			        pager:true,
			        nav:true,
			        speed: 500,
			        namespace: "callbacks",
			        before: function () {
			          $('.events').append("<li>before event fired.</li>");
			        },
			        after: function () {
			          $('.events').append("<li>after event fired.</li>");
			        }
			      });

			    });
			  </script>